//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acrolinx.Sdk.Sidebar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acrolinx.Sdk.Sidebar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconConnected {
            get {
                object obj = ResourceManager.GetObject("iconConnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconConnecting {
            get {
                object obj = ResourceManager.GetObject("iconConnecting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconDisconnected {
            get {
                object obj = ResourceManager.GetObject("iconDisconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SDK_ABOUT_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("SDK_ABOUT_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SDK_ABOUT_LABEL_ASSEMBLYNAME {
            get {
                return ResourceManager.GetString("SDK_ABOUT_LABEL_ASSEMBLYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string SDK_ABOUT_LABEL_COPYTOCLIPBOARD {
            get {
                return ResourceManager.GetString("SDK_ABOUT_LABEL_COPYTOCLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SDK_ABOUT_LABEL_PATH {
            get {
                return ResourceManager.GetString("SDK_ABOUT_LABEL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrolinx for .
        /// </summary>
        internal static string SDK_ABOUT_LABEL_PRODUCTNAME {
            get {
                return ResourceManager.GetString("SDK_ABOUT_LABEL_PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string SDK_ABOUT_LABEL_VERSION {
            get {
                return ResourceManager.GetString("SDK_ABOUT_LABEL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string SDK_OPTION_BUTTON_VALIDATE {
            get {
                return ResourceManager.GetString("SDK_OPTION_BUTTON_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrolinx Options.
        /// </summary>
        internal static string SDK_OPTION_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("SDK_OPTION_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string SDK_OPTION_GROUP_LOGGING {
            get {
                return ResourceManager.GetString("SDK_OPTION_GROUP_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string SDK_OPTION_LABEL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string SDK_OPTION_LABEL_BUTTON_OK {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory:.
        /// </summary>
        internal static string SDK_OPTION_LABEL_DIRECTORY {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select in Sidebar.
        /// </summary>
        internal static string SDK_OPTION_LABEL_SELECTINSIDEBAR {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_SELECTINSIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        internal static string SDK_OPTION_LABEL_SERVERADDRESS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_SERVERADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_CONNECTING {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server doesn&apos;t seem to be responding. Is the address correct?.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_FAILURE {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is online, but it doesn&apos;t support the sidebar feature..
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_SIDEBAR_FAILURE {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_SIDEBAR_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is online and everything loads properly..
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_SUCCESS", resourceCulture);
            }
        }
    }
}
