//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acrolinx.Sdk.Sidebar.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acrolinx.Sdk.Sidebar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconConnected {
            get {
                object obj = ResourceManager.GetObject("iconConnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconConnecting {
            get {
                object obj = ResourceManager.GetObject("iconConnecting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconDisconnected {
            get {
                object obj = ResourceManager.GetObject("iconDisconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string SDK_OPTION_BUTTON_VALIDATE {
            get {
                return ResourceManager.GetString("SDK_OPTION_BUTTON_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acrolinx Options ähnelt.
        /// </summary>
        internal static string SDK_OPTION_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("SDK_OPTION_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        internal static string SDK_OPTION_GROUP_LOGGING {
            get {
                return ResourceManager.GetString("SDK_OPTION_GROUP_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_BUTTON_OK {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory: ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_DIRECTORY {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select in Sidebar ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_SELECTINSIDEBAR {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_SELECTINSIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Address: ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_SERVERADDRESS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_SERVERADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting... ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_CONNECTING {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server doesn&apos;t seem to be responding. Is the address correct? ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_FAILURE {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not connected ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server is online and everything loads properly. ähnelt.
        /// </summary>
        internal static string SDK_OPTION_LABEL_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("SDK_OPTION_LABEL_STATUS_SUCCESS", resourceCulture);
            }
        }
    }
}
